wikilabels:
  form_directory: forms/enabled
  form_i18n_directory: forms/i18n

wsgi:
  application_root: ""
  url_prefix: ""

database:
  host: localhost
  dbname: wikilabels

oauth:
  mw_uri: https://www.mediawiki.org/w/index.php
