wsgi:
  host: localhost:8080
  form_directory: forms/enabled
  application_root: /labels
  url_prefix: /labels

database:
  host: localhost
  user: wikilabels
  database: wikilabels
  password: wikilabels-admin

oauth:
  mw_uri: https://www.mediawiki.org/w/index.php
  key: b321d4c978793c5e0143b743e384ad98
  secret: 8cad97660fa9db099e96277ebe3dd6eef89b8421
